<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>DevOps on bits-pieces</title><link>https://l10178.github.io/bits-pieces/devops/</link><description>Recent content in DevOps on bits-pieces</description><generator>Hugo -- gohugo.io</generator><language>zh-CN</language><lastBuildDate>Fri, 19 Mar 2021 23:54:37 +0800</lastBuildDate><atom:link href="https://l10178.github.io/bits-pieces/devops/index.xml" rel="self" type="application/rss+xml"/><item><title>MySQL5.7升级至8.0</title><link>https://l10178.github.io/bits-pieces/devops/mysql5.7to8.0/</link><pubDate>Wed, 29 Dec 2021 23:54:37 +0800</pubDate><guid>https://l10178.github.io/bits-pieces/devops/mysql5.7to8.0/</guid><description>MySQL 5.7 升级至 8.0，程序适配以及踩坑记录。
代码适配方案 mysql-connector-java.jar 升级到 8.0.21 版本。 com.mysql.jdbc.Driver 更换为 com.mysql.cj.jdbc.Driver。 链接 url 里指定 useSSL=false。 链接 url 中显式指定时区，增加 serverTimezone=Asia/Shanghai。 兼容性问题 com.mysql.jdbc.exceptions.jdbc4 在 MySQL Connector 8 中不存在。
将 mysql-connector-java 版本，升级到 8.0 后，如果项目中有使用 mysql 的 Exception 类，编译时会收到以下错误
error: package com.mysql.jdbc.exceptions.jdbc4 does not exist [ERROR] import com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException; [ERROR] import com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException; MySQL 在 8.0 版本重用了现有的 java.sql 异常类，取消了 exceptions.jdbc4 的异常类，整改的异常映射关系如下。
5.7 版本异常类 8.0 版本异常类 com.</description></item></channel></rss>